PORTNAME=		ppsspp
PKGNAMEPREFIX=		libretro-

COMMENT=		Libretro core for games/retroarch
MASTERDIR=		${.CURDIR}/../ppsspp

PPSSPP_SLAVE=		libretro

PLIST=
PLIST_FILES=		lib/libretro/${PORTNAME}_libretro.so

OPTIONS_DEFINE=	

.include "${MASTERDIR}/Makefile"
